# Generated by Django 5.2.5 on 2025-10-26 07:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field', '0011_fieldequipment_price_per_unit_alter_equipment_type_and_more'),
        ('users', '0003_alter_partner_options_alter_regular_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('canceled', 'Cancelada')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='field.field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='BookingExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='booking.booking')),
                ('field_equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_extras', to='field.fieldequipment')),
            ],
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['field', 'start', 'end', 'status'], name='booking_boo_field_i_40c1a9_idx'),
        ),
    ]
