# Generated by Django 5.2.5 on 2025-08-31 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='fields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('0', 'Regular'), ('1', 'Partner')], default='Regular', max_length=50),
        ),
    ]
