# Generated by Django 5.2.5 on 2025-10-25 20:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_partner_fields_alter_user_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Socio', 'verbose_name_plural': 'Socios'},
        ),
        migrations.AlterModelOptions(
            name='regular',
            options={'verbose_name': 'Perfil Regular', 'verbose_name_plural': 'Perfiles Regular'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='bank_count',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='fields',
        ),
        migrations.AddField(
            model_name='partner',
            name='cci',
            field=models.CharField(default=12345678911234567891, help_text='Número CCI de 20 dígitos (Perú).', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{20}$', 'El CCI debe tener exactamente 20 dígitos.')], verbose_name='Cuenta Interbancaria (CCI)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(limit_choices_to={'rol': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to='users.user'),
        ),
        migrations.AlterField(
            model_name='regular',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regular_profile', to='users.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('regular', 'Regular'), ('partner', 'Partner')], default='regular', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['rol'], name='users_user_rol_5562e3_idx'),
        ),
    ]
