# Generated by Django 5.2.5 on 2025-09-03 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_initial'),
        ('users', '0002_alter_partner_fields_alter_user_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='field',
        ),
        migrations.RemoveField(
            model_name='field',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='field',
            name='verificado',
        ),
        migrations.AlterField(
            model_name='field',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='users.user'),
        ),
        migrations.CreateModel(
            name='FieldEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_fields', to='field.equipment')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_equipments', to='field.field')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='equipment_extra',
            field=models.ManyToManyField(blank=True, related_name='fields', through='field.FieldEquipment', to='field.equipment'),
        ),
    ]
