# Generated by Django 5.2.5 on 2025-09-03 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0003_remove_equipment_field_remove_field_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='equipment_extra',
            new_name='extra_equipment',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='precio_hora',
            new_name='price_hour',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='tipo',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='fieldequipment',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('balon_futbol', 'Balón de Fútbol'), ('balon_basket', 'Balón de Básquet'), ('balon_voley', 'Balón de Vóley'), ('chalecos', 'Chalecos de Entrenamiento'), ('conos', 'Conos de Entrenamiento'), ('arcos_portatiles', 'Arcos Portátiles'), ('cronometro', 'Cronómetro'), ('raquetas_tenis', 'Raquetas de Tenis'), ('pelotas_tenis', 'Pelotas de Tenis'), ('paletas_paddle', 'Paletas de Padel'), ('pelotas_paddle', 'Pelotas de Padel'), ('cuerda_saltar', 'Cuerdas para Saltar'), ('colchonetas', 'Colchonetas'), ('pesas_mancuernas', 'Pesas / Mancuernas')], default='balon_futbol', max_length=50),
        ),
        migrations.AddField(
            model_name='fieldequipment',
            name='stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
