# Generated by Django 5.2.5 on 2025-09-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0004_rename_descripcion_equipment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='field_images/'),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('futbol', 'Fútbol'), ('basket', 'Básquet'), ('voley', 'Vóley'), ('tenis', 'Tenis'), ('paddle', 'Paddle'), ('multiuso', 'Multiuso')], default='multiuso', max_length=100),
        ),
    ]
