# Generated by Django 5.2.5 on 2025-09-14 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0005_field_image_alter_field_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='field_albums/')),
                ('is_primary', models.BooleanField(default=False, help_text='Marca esta imagen como la principal del campo.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Orden de la imagen en el álbum.')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='field.field')),
            ],
            options={
                'ordering': ['sort_order'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('field',), name='unique_primary_image_per_field')],
            },
        ),
    ]
