# Generated by Django 5.2.5 on 2025-09-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0006_rename_image_field_cover_image_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='cover_image',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('balon_futbol', 'Balón de Fútbol'), ('balon_basket', 'Balón de Básquet'), ('balon_voley', 'Vóley'), ('chalecos', 'Chalecos de Entrenamiento'), ('conos', 'Conos de Entrenamiento'), ('arcos_portatiles', 'Arcos Portátiles'), ('cronometro', 'Cronómetro'), ('raquetas_tenis', 'Raquetas de Tenis'), ('pelotas_tenis', 'Pelotas de Tenis'), ('paletas_paddle', 'Paletas de Padel'), ('pelotas_paddle', 'Pelotas de Padel'), ('cuerda_saltar', 'Cuerdas para Saltar'), ('colchonetas', 'Colchonetas'), ('pesas_mancuernas', 'Pesas / Mancuernas')], default='balon_futbol', max_length=50),
        ),
    ]
