# Generated by Django 5.2.5 on 2025-09-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0007_remove_field_cover_image_alter_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='has_lights',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('futbol', 'Fútbol'), ('basket', 'Básquet'), ('voley', 'Vóley'), ('tenis', 'Tenis'), ('multiuso', 'Multiuso')], default='multiuso', max_length=100),
        ),
    ]
