# Generated by Django 5.2.5 on 2025-09-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0008_field_has_lights_alter_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('futbol', 'Fútbol'), ('basket', 'Basketball'), ('voley', 'Volleyball'), ('tenis', 'Tenis'), ('multiuso', 'Multiuso')], default='multiuso', max_length=100),
        ),
    ]
