# Generated by Django 5.2.5 on 2025-10-26 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0010_alter_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldequipment',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('balon_futbol', 'Balón de Fútbol'), ('balon_basket', 'Balón de Básquet'), ('balon_voley', 'Balón de Vóley'), ('chalecos', 'Chalecos de Entrenamiento'), ('conos', 'Conos de Entrenamiento'), ('cronometro', 'Cronómetro'), ('raquetas_tenis', 'Raquetas de Tenis'), ('pelotas_tenis', 'Pelotas de Tenis'), ('cuerda_saltar', 'Cuerdas para Saltar'), ('colchonetas', 'Colchonetas'), ('pesas_mancuernas', 'Pesas / Mancuernas')], default='balon_futbol', max_length=50),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('futbol', 'Fútbol'), ('basket', 'Basketball'), ('voley', 'Volleyball'), ('tenis', 'Tenis'), ('multiuso', 'Multiuso')], default='multiuso', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='fieldequipment',
            constraint=models.UniqueConstraint(fields=('field', 'equipment'), name='uniq_field_equipment'),
        ),
    ]
